apm-server:
  host: "localhost:8200"
  rum:
    enabled: true
  kibana:
    enabled: true
    host: "kibana:5601"

output.elasticsearch:
  hosts: ["elasticsearch:9200"]

setup:
  kibana:
    host: "kibana:5601"
  template.settings:
  index:
    number_of_replicas: 0

queue.mem.events: 4096

max_procs: 4